### ISSUE TITLE
Charm doesn't advertise ports, juju expose does nothing

### ISSUE THREAD

**Issue by kyrofa** [alchemy-charmers/charm-gitlab#13]
The charm doesn't use open-port at all, for either of the two ports required for gitlab to be totally usable (80 and 22). It thus _requires_ the use of the haproxy charm on any cloud other than lxd (i.e. ones that require `juju expose`).

**Comment by chris-sanders** [comment]
How are you testing this, can you recreate it? There is certainly code for opening ports in the charm and I've used it on AWS and OpenStack in the past. If it's not working that's indeed a bug and unintended.

**Comment by kyrofa** [comment]
Indeed, haproxy works properly. For gitlab it's trivial to recreate, you can see a problem as soon as you deploy it in `juju status`:

```
$ juju status
Model   Controller  Cloud/Region         Version  SLA          Timestamp
gitlab  overlord    localhost/localhost  2.6.10   unsupported  09:56:16-08:00

App         Version  Status  Scale  Charm       Store       Rev  OS      Notes
gitlab      1.0      active      1  gitlab      jujucharms   14  ubuntu  
haproxy     0.1.6    active      1  haproxy     jujucharms    4  ubuntu  
postgresql  10.10    active      1  postgresql  jujucharms  199  ubuntu  
redis       4.0.11   active      1  redis       jujucharms    1  ubuntu  

Unit           Workload  Agent  Machine  Public address  Ports           Message
gitlab/0*      active    idle   0        10.164.166.110                  GitLab installed and configured
haproxy/0*     active    idle   8        10.164.166.43   80/tcp,222/tcp  
postgresql/0*  active    idle   4        10.164.166.246  5432/tcp        Live master (10.10)
redis/0*       active    idle   5        10.164.166.113  6379/tcp        Redis available
```

Note that `gitlab/0` advertises no ports. When you run `juju expose`, correspondingly, no ports are opened.

**Comment by devec0** [comment]
This has been added to the latest released version on the charmstore, the port will open 80 and 22 once configuration is complete. The `ssh_port` setting still controls the reverse proxy and UI port, but the charm always opens port 22 regardless on the local unit. It will of course only be exposed if `juju expose` is used on the gitlab application.
