### ISSUE TITLE
update charm on charmstore

### ISSUE THREAD

**Issue by dodys** [alchemy-charmers/charm-gitlab#30]
Hey,

Apparently the charm on charmstore still doesn't include the pgp key fix (last merged commit).
The same is true for charm-gitlab-runner

**Comment by chris-sanders** [comment]
Thanks, I've just pushed gitlab with this included. gitlab-runner requires this change I'll test it next, but I believe it will need a bit more work b/c already installed runners won't be updated on charm-upgrade. I'll check on that and see if I can get a fix for it soon.
